"""Add exchange, trade_type, event_type and update nullability

Revision ID: b5b52e151986
Revises: a1b2c3d4e5f6
Create Date: 2025-10-26 12:34:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import Enum types if needed for PostgreSQL ENUM creation
from app.schemas import TradeType, EventType


# revision identifiers, used by Alembic.
revision: str = 'b5b52e151986'
down_revision: Union[str, None] = 'a1b2c3d4e5f6' # Points to the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - manually verified ###

    # Create new ENUM types first (required for PostgreSQL)
    trade_type_enum = sa.Enum(TradeType, name='trade_type_enum')
    trade_type_enum.create(op.get_bind(), checkfirst=False) # checkfirst=False avoids error if type exists

    event_type_enum = sa.Enum(EventType, name='event_type_enum')
    event_type_enum.create(op.get_bind(), checkfirst=False)

    # Add new columns
    op.add_column('transactions', sa.Column('exchange', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('trade_type', trade_type_enum, nullable=True))
    op.add_column('transactions', sa.Column('event_type', event_type_enum, nullable=True))

    # Alter nullability of existing columns
    op.alter_column('transactions', 'security_id',
               existing_type=sa.INTEGER(),
               nullable=False) # Make non-nullable
    op.alter_column('transactions', 'side',
               existing_type=sa.VARCHAR(length=4), # Assuming length based on 'Buy'/'Sell'
               type_=sa.Enum('BUY', 'SELL', name='trade_side_enum'), # Ensure type is correct ENUM
               nullable=True, # Make nullable
               existing_nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True) # Make nullable
    op.alter_column('transactions', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True) # Make nullable

    # Create indexes for new columns
    op.create_index(op.f('ix_transactions_event_type'), 'transactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_transactions_exchange'), 'transactions', ['exchange'], unique=False)
    op.create_index(op.f('ix_transactions_trade_type'), 'transactions', ['trade_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - manually verified ###
    op.drop_index(op.f('ix_transactions_trade_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_exchange'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_event_type'), table_name='transactions')

    # Revert nullability changes
    op.alter_column('transactions', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'side',
               existing_type=sa.Enum('BUY', 'SELL', name='trade_side_enum'),
               nullable=False,
               existing_nullable=True)
    op.alter_column('transactions', 'security_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Drop new columns
    op.drop_column('transactions', 'event_type')
    op.drop_column('transactions', 'trade_type')
    op.drop_column('transactions', 'exchange')

    # Drop the ENUM types (required for PostgreSQL)
    sa.Enum(EventType, name='event_type_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(TradeType, name='trade_type_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###